name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble the Debug .apk
      run: ./gradlew assembleDebug
    - name: Create and Release the Debug artifact
      uses: actions/upload-artifact@v3
      with:
        name: osudroid-rx
        path: build/outputs/apk/debug/app-debug.apk
